---
collections:
  - name: ansible.posix
    version: 2.1.0

roles:
  - name: linux-system-roles.storage
    version: 1.19.1
  - name: ded-isshin.pdns-ansible
    src: ssh://git@github.com/ded-isshin/pdns-ansible.git
    scm: git
    version: master
  - name: robertdebock.storage
    version: 6.0.4
  - name: robertdebock.bootstrap
    version: 7.1.6
  - name: robertdebock.core_dependencies
    version: 2.2.16
  - name: robertdebock.hashicorp
    version: 3.4.11
  - name: robertdebock.vault
    version: 6.1.8
  - name: robertdebock.vault_configuration
    version: 5.2.2
  - name: robertdebock.vault_initialize
    version: 1.0.4
  - name: robertdebock.gitlab
    version: 1.14.1
  - name: robertdebock.gitlab_runner
    version: 6.0.1
  - name: nginxinc.nginx
    version: 0.25.0
  - name: nginxinc.nginx_config
    version: 0.7.1
  # - name: cloudalchemy.coredns
  #   version: 2.0.0
  # - name: igor_nikiforov.etcd
  #   version: v1.0.0
